baseURL = "https://yyccblog.cn/"
title = '呓语成谶'
theme = "archie"
copyright = "© yuryqwer"
locale = "zh-cn"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

[frontmatter]
	date = ["date"]

[pagination]
  pagerSize = 10 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "你看，我就说吧，________。"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	favicon = "/img/favicon.svg"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/yuryqwer"

[[params.social]]
name = "邮箱"
icon = "mail"
url = "mailto:yuryqwer@outlook.com"

[[params.social]]
name = "手机"
icon = "phone"
url = "tel:+86-158-9592-6915"

# Main menu Items

[[menu.main]]
name = "主页"
url = "/"
weight = 1

[[menu.main]]
name = "博客"
url = "/posts"
weight = 2

[[menu.main]]
name = "简介"
url = "/about"
weight = 3

[[menu.main]]
name = "标签"
url = "/tags"
weight = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'