baseURL = "https://yyccblog.cn/"
title = '呓语成谶'
theme = "archie"
copyright = "© yuryqwer"
locale = "zh-cn"
summaryLength = 20 # 主页的文章摘要长度，单位为字符
enableGitInfo = true # 启用 Git 信息支持，以显示文章的最后修改时间

# Code Highlight
[markup.highlight]
	noClasses = false # 禁用内联样式，使用 CSS 类来控制代码高亮的样式
	lineNos = "inline"

[frontmatter]
	date = ["date"]

[pagination]
	pagerSize = 3 # 每页显示的文章数量

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "你看，我就说吧，________。"
	mathjax = false # disable MathJax support
	katex = true # enable KaTeX support
	favicon = "/img/favicon.svg"
	customCSS = ["css/custom.css", "css/code.css"]
	customJS = ["js/giscus-theme.js", "js/code.js"]
	mainSections = ["posts"] # sections to include in search index
	comments = true # enable comments via giscus

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^GISCUS_']

# Social Tags

[[params.social]]
	name = "GitHub"
	icon = "github"
	url = "https://github.com/yuryqwer"

[[params.social]]
	name = "邮箱"
	icon = "mail"
	url = "mailto:yuryqwer@outlook.com"

[[params.social]]
	name = "手机"
	icon = "phone"
	url = "tel:+86-158-9592-6915"

# Main menu Items

[[menu.main]]
	name = "主页"
	url = "/"
	weight = 1

[[menu.main]]
	name = "归档"
	url = "/posts"
	weight = 2

# [[menu.main]]
# 	name = "简介"
# 	url = "/about"
# 	weight = 3

[[menu.main]]
	name = "标签"
	url = "/tags"
	weight = 4

[[menu.main]]
	name = "搜索"
	url = "/search"
	weight = 5
